# Generated by Django 6.0.5 on 2026-05-25 07:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seleccion', models.CharField(choices=[('local', 'Gana local'), ('empate', 'Empate'), ('visitante', 'Gana visitante'), ('sobre', 'Over 2.5'), ('bajo', 'Under 2.5'), ('si', 'Sí'), ('no', 'No')], max_length=15, verbose_name='Selección')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Formato decimal europeo, ej. 2.5000', max_digits=10, verbose_name='Valor de la cuota')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('es_ganadora', models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Es ganadora?')),
                ('liquidada_en', models.DateTimeField(blank=True, null=True, verbose_name='Liquidada en')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'eventos_cuota',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del evento')),
                ('deporte', models.CharField(default='futbol', max_length=50, verbose_name='Deporte')),
                ('equipo_local', models.CharField(max_length=100, verbose_name='Equipo local')),
                ('equipo_visitante', models.CharField(max_length=100, verbose_name='Equipo visitante')),
                ('inicia_en', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=15, verbose_name='Estado')),
                ('resultado', models.JSONField(blank=True, help_text='{"local": 2, "visitante": 1}', null=True, verbose_name='Resultado final')),
                ('es_momento_critico', models.BooleanField(default=False, verbose_name='¿Momento crítico?')),
                ('momento_critico_desde', models.DateTimeField(blank=True, null=True, verbose_name='Momento crítico desde')),
                ('ultimo_cambio_estado', models.DateTimeField(auto_now_add=True, verbose_name='Último cambio de estado')),
                ('apuestas_cerradas_en', models.DateTimeField(blank=True, null=True, verbose_name='Apuestas cerradas en')),
                ('desempate_fair_play', models.JSONField(blank=True, help_text='{"tarjetas_amarillas_local": 2, "tarjetas_rojas_local": 0, ...}', null=True, verbose_name='Desempate fair play')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos_evento',
                'indexes': [models.Index(fields=['estado', 'inicia_en'], name='eventos_eve_estado_320ea4_idx'), models.Index(fields=['es_momento_critico', 'momento_critico_desde'], name='eventos_eve_es_mome_6744d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialCuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor histórico')),
                ('registrado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='events.cuota', verbose_name='Cuota')),
            ],
            options={
                'verbose_name': 'Historial de cuota',
                'verbose_name_plural': 'Historiales de cuotas',
                'db_table': 'eventos_historialcuota',
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1x2', '1X2 (Resultado final)'), ('sobre_bajo', 'Over/Under 2.5 goles'), ('ambos_anotan', 'Ambos equipos anotan (BTTS)'), ('handicap_asiatico', 'Hándicap asiático')], max_length=20, verbose_name='Tipo de mercado')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('suspendido', 'Suspendido'), ('cerrado', 'Cerrado'), ('liquidado', 'Liquidado')], default='abierto', max_length=15, verbose_name='Estado')),
                ('suspendido_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Suspendido hasta')),
                ('motivo_suspension', models.CharField(blank=True, choices=[('evento_critico', 'Evento crítico (gol, expulsión)'), ('manual', 'Suspensión manual del operador'), ('pre_partido', 'Cierre pre-partido'), ('liquidacion', 'Liquidación en curso')], max_length=20, null=True, verbose_name='Motivo de suspensión')),
                ('suspendido_por', models.CharField(blank=True, choices=[('SISTEMA', 'Sistema'), ('OPERADOR', 'Operador')], max_length=20, null=True, verbose_name='Suspendido por')),
                ('margen_operador', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Margen de beneficio del operador, ej. 0.05 = 5%', max_digits=5, verbose_name='Margen del operador')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercados', to='events.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'db_table': 'eventos_mercado',
                'unique_together': {('evento', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='events.mercado', verbose_name='Mercado'),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('mercado', 'seleccion')},
        ),
    ]
