# Generated by Django 6.0.4 on 2026-05-29 22:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(help_text='Tipo de evento, ej. apuesta_creada', max_length=50)),
                ('payload', models.TextField(help_text='Datos del evento en texto')),
                ('hash_anterior', models.CharField(blank=True, max_length=64)),
                ('hash_actual', models.CharField(max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'dashboard_auditoria',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
