# Generated by Django 6.0.4 on 2026-05-25 14:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('temporal_7', 'Temporal (7 días)'), ('temporal_30', 'Temporal (30 días)'), ('temporal_90', 'Temporal (90 días)'), ('indefinida', 'Indefinida')], max_length=20, verbose_name='Tipo de exclusión')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusiones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Autoexclusión',
                'verbose_name_plural': 'Autoexclusiones',
                'db_table': 'usuarios_autoexclusion',
                'indexes': [models.Index(fields=['usuario', 'activa', 'fecha_fin'], name='usuarios_au_usuario_483fe3_idx')],
            },
        ),
        migrations.CreateModel(
            name='LimiteDeposito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10, verbose_name='Período')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Monto límite')),
                ('enfriamiento_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Enfriamiento hasta (cooldown)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limites_deposito', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Límite de depósito',
                'verbose_name_plural': 'Límites de depósito',
                'db_table': 'usuarios_limitedeposito',
                'unique_together': {('usuario', 'periodo')},
            },
        ),
    ]
