# Generated by Django 6.0.5 on 2026-05-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responsible_gaming", "0002_limite_deposito_aumento_pendiente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("regla", models.CharField(max_length=80, verbose_name="Regla")),
                ("descripcion", models.TextField(verbose_name="Descripcion")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        verbose_name="Direccion IP",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("revisado", "Revisado"),
                            ("descartado", "Descartado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_sospechosas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad sospechosa",
                "verbose_name_plural": "Actividades sospechosas",
                "db_table": "responsible_gaming_suspiciousactivity",
                "indexes": [
                    models.Index(
                        fields=["regla", "ip_address", "fecha_creacion"],
                        name="responsible_regla_8f1ae5_idx",
                    ),
                    models.Index(
                        fields=["estado", "fecha_creacion"],
                        name="responsible_estado_d2b343_idx",
                    ),
                ],
            },
        ),
    ]
