# Generated by Django 6.0.5 on 2026-05-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_gaming', '0003_suspiciousactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoexclusion',
            options={'verbose_name': 'Autoexclusion', 'verbose_name_plural': 'Autoexclusiones'},
        ),
        migrations.AlterModelOptions(
            name='limitedeposito',
            options={'verbose_name': 'Limite de deposito', 'verbose_name_plural': 'Limites de deposito'},
        ),
        migrations.AlterField(
            model_name='autoexclusion',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='autoexclusion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='autoexclusion',
            name='tipo',
            field=models.CharField(choices=[('temporal_7', 'Temporal (7 días)'), ('temporal_30', 'Temporal (30 días)'), ('temporal_90', 'Temporal (90 días)'), ('indefinida', 'Indefinida')], max_length=20, verbose_name='Tipo de exclusion'),
        ),
        migrations.AlterField(
            model_name='limitedeposito',
            name='enfriamiento_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enfriamiento hasta'),
        ),
        migrations.AlterField(
            model_name='limitedeposito',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion'),
        ),
        migrations.AlterField(
            model_name='limitedeposito',
            name='monto',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Monto limite'),
        ),
        migrations.AlterField(
            model_name='limitedeposito',
            name='periodo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10, verbose_name='Periodo'),
        ),
    ]
