# Generated by Django 6.0.5 on 2026-05-25 07:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('combinada', 'Combinada')], default='simple', max_length=20, verbose_name='Tipo de apuesta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('aceptada', 'Aceptada'), ('ganada', 'Ganada'), ('perdida', 'Perdida'), ('cash_out', 'Cash-out'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('monto_apostado', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Monto apostado (stake)')),
                ('cuota_total', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18, verbose_name='Cuota total')),
                ('ganancia_potencial', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Ganancia potencial')),
                ('ganancia_real', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Ganancia real (payout)')),
                ('monto_cash_out', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Monto de cash-out')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación')),
                ('fecha_liquidacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de liquidación')),
                ('clave_idempotencia', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Clave de idempotencia')),
                ('verificacion_juego_responsable', models.BooleanField(default=False, verbose_name='¿Verificó juego responsable?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
                'db_table': 'apuestas_apuesta',
            },
        ),
        migrations.CreateModel(
            name='PiernaApuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuota_al_momento', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cuota al momento de la apuesta')),
                ('es_ganadora', models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Es ganadora?')),
                ('apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piernas', to='betting.apuesta', verbose_name='Apuesta')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.cuota', verbose_name='Cuota seleccionada')),
            ],
            options={
                'verbose_name': 'Pierna de apuesta',
                'verbose_name_plural': 'Piernas de apuestas',
                'db_table': 'apuestas_pierna',
            },
        ),
        migrations.AddIndex(
            model_name='apuesta',
            index=models.Index(fields=['usuario', 'estado', 'fecha_creacion'], name='apuestas_ap_usuario_c6341f_idx'),
        ),
        migrations.AddIndex(
            model_name='apuesta',
            index=models.Index(fields=['estado', 'fecha_liquidacion'], name='apuestas_ap_estado_d37e9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='piernaapuesta',
            unique_together={('apuesta', 'cuota')},
        ),
    ]
