# Generated by Django 6.0.5 on 2026-05-25 07:12

import apps.users.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[apps.users.validators.validar_dni], verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(validators=[apps.users.validators.validar_edad], verbose_name='Fecha de nacimiento')),
                ('estado_kyc', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado')], default='pendiente', max_length=30, verbose_name='Estado KYC')),
                ('fecha_verificacion_kyc', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación KYC')),
                ('telefono', models.CharField(blank=True, max_length=9, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'db_table': 'usuarios_perfil',
            },
        ),
    ]
