# Generated by Django 6.0.5 on 2026-05-25 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cuenta', models.CharField(choices=[('billetera_usuario', 'Billetera de usuario'), ('casa', 'Cuenta de la casa'), ('apuestas_pendientes', 'Apuestas pendientes'), ('bonos', 'Bonos')], max_length=30, verbose_name='Tipo de cuenta')),
                ('moneda', models.CharField(default='FIC', help_text='FIC = Fichas virtuales', max_length=3, verbose_name='Moneda')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(blank=True, help_text='Null para cuentas del sistema (casa, pendientes, bonos)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'billetera_cuenta',
                'unique_together': {('usuario', 'tipo_cuenta')},
            },
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Monto')),
                ('direccion', models.CharField(choices=[('DEBITO', 'Débito (salida)'), ('CREDITO', 'Crédito (entrada)')], max_length=10, verbose_name='Dirección')),
                ('id_transaccion', models.UUIDField(db_index=True, verbose_name='ID de transacción')),
                ('tipo_asiento', models.CharField(choices=[('recarga', 'Recarga de fichas'), ('retiro', 'Retiro simulado de fichas'), ('bloqueo_apuesta', 'Bloqueo por apuesta'), ('ganancia_apuesta', 'Ganancia de apuesta'), ('perdida_apuesta', 'Pérdida de apuesta'), ('cash_out', 'Cash-out anticipado'), ('bono_acreditado', 'Abono de bono'), ('bono_debitado', 'Débito de bono')], max_length=20, verbose_name='Tipo de asiento')),
                ('id_referencia', models.UUIDField(blank=True, null=True, verbose_name='ID de referencia')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='wallet.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'db_table': 'billetera_asiento',
                'ordering': ['fecha_creacion'],
                'indexes': [models.Index(fields=['id_transaccion'], name='billetera_a_id_tran_6819d9_idx'), models.Index(fields=['cuenta', 'fecha_creacion'], name='billetera_a_cuenta__7b4b01_idx')],
            },
        ),
    ]
