# Generated by Django 6.0.5 on 2026-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo_asiento',
            field=models.CharField(choices=[('recarga', 'Recarga de fichas'), ('retiro', 'Retiro simulado de fichas'), ('transferencia', 'Transferencia entre usuarios'), ('bloqueo_apuesta', 'Bloqueo por apuesta'), ('ganancia_apuesta', 'Ganancia de apuesta'), ('perdida_apuesta', 'Pérdida de apuesta'), ('cash_out', 'Cash-out anticipado'), ('bono_acreditado', 'Abono de bono'), ('bono_debitado', 'Débito de bono')], max_length=20, verbose_name='Tipo de asiento'),
        ),
    ]
